### PR TITLE
added custom user marp themes links

### PR DESCRIPTION
**Pull request by engineerjoe440**
I found a useful example from a community member who posted their work with a license, and I thought that it was useful, and might be worth linking to in the themes README. Thought this might be helpful to other newbies like me!

### CODE REVIEW

**Comment by yhatt** [comment]
Thanks for opening PR.

However, we hope to collect community resources into the entrance repository [marp-team/marp](https://github.com/marp-team/marp) instead of Marp Core, for user's discoverability.

In addition, need to confirmation of the original author to introduce in Marp team official repository.

**Comment by yhatt** [comment]
We don't want to collect examples in Marp Core, so close it.

If you think there is a worth to collect repositories about Marp anyway, try to create your own "awesome-marp" repository referring to [many awesome lists](https://github.com/sindresorhus/awesome)!

**Comment by engineerjoe440** [comment]
Hmm... I think that's somewhat disappointing. I was hoping that this might spark discussion about showing a full theme example, and show what others might be using the project for.

I think that's a good point about the awesome-marp repository, but it seems that it would be useful to see a fill and comprehensive theme example in addition to the simple examples shown in documentation. It seems appropriate to me to have this sort of documentation available in multiple places. Especially where the base themes are stored in source.

Best of luck to you.

**Comment by yhatt** [comment]
In short, Marp team has no time to maintain helpful resources from community for now. We think it's the best to leave its role to community instead of marp-team organization.

**Pull request closed without merging**
